# Generated by Django 4.2.16 on 2024-12-08 16:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=64, unique=True)),
                ('organization_address', models.CharField(blank=True, default='none', max_length=64)),
                ('organization_coordinates', models.CharField(blank=True, default='none', max_length=64)),
                ('url', models.CharField(blank=True, default='none', max_length=64)),
                ('description', models.TextField()),
                ('publish_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=64, unique=True)),
                ('person_address', models.CharField(blank=True, default='none', max_length=64)),
                ('person_coordinates', models.CharField(blank=True, default='none', max_length=64)),
                ('person_email', models.CharField(blank=True, default='none', max_length=64)),
                ('person_mobile', models.CharField(blank=True, default='none', max_length=64)),
                ('person_website', models.CharField(blank=True, default='none', max_length=64)),
                ('person_linkedin', models.CharField(blank=True, default='none', max_length=64)),
                ('person_facebook', models.CharField(blank=True, default='none', max_length=64)),
                ('person_instagram', models.CharField(blank=True, default='none', max_length=64)),
                ('person_tiktok', models.CharField(blank=True, default='none', max_length=64)),
                ('description', models.TextField()),
                ('publish_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DomainName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=64, unique=True)),
                ('name_server_1', models.CharField(blank=True, default='none', max_length=64)),
                ('name_server_2', models.CharField(blank=True, default='none', max_length=64)),
                ('name_server_3', models.CharField(blank=True, default='none', max_length=64)),
                ('description', models.TextField()),
                ('create_date', models.DateField(default=datetime.datetime(2024, 12, 8, 16, 29, 21, 607326, tzinfo=datetime.timezone.utc))),
                ('update_date', models.DateField(default=datetime.datetime(2024, 12, 8, 16, 29, 21, 607331, tzinfo=datetime.timezone.utc))),
                ('expire_date', models.DateField(default=datetime.datetime(2024, 12, 8, 16, 29, 21, 607335, tzinfo=datetime.timezone.utc))),
                ('administrative_contact', models.ForeignKey(db_column='person_name', on_delete=django.db.models.deletion.CASCADE, to='info_gathering.personinfo', to_field='person_name')),
                ('organization_name', models.ForeignKey(db_column='organization_name', on_delete=django.db.models.deletion.CASCADE, to='info_gathering.organizationinfo', to_field='organization_name')),
            ],
        ),
    ]
