# Generated by Django 4.2.16 on 2024-12-09 22:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info_gathering', '0005_alter_domainname_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainname',
            name='administrative_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_gathering.personinfo', to_field='name'),
        ),
        migrations.AlterField(
            model_name='domainname',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 9, 22, 49, 51, 131092, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='domainname',
            name='expire_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 9, 22, 49, 51, 131105, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='domainname',
            name='update_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 9, 22, 49, 51, 131098, tzinfo=datetime.timezone.utc)),
        ),
    ]
