# Generated by Django 4.2.16 on 2024-12-09 23:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_gathering', '0007_alter_domainname_create_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domainname',
            name='administrative_contact',
        ),
        migrations.AlterField(
            model_name='domainname',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 9, 23, 19, 37, 982177, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='domainname',
            name='expire_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 9, 23, 19, 37, 982186, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='domainname',
            name='update_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 9, 23, 19, 37, 982182, tzinfo=datetime.timezone.utc)),
        ),
    ]
