# Generated by Django 4.2.16 on 2024-12-09 23:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info_gathering', '0008_remove_domainname_administrative_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainname',
            name='administrative_contact',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='info_gathering.personinfo', to_field='name'),
        ),
        migrations.AlterField(
            model_name='domainname',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 9, 23, 20, 38, 705247, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='domainname',
            name='expire_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 9, 23, 20, 38, 705255, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='domainname',
            name='update_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 9, 23, 20, 38, 705252, tzinfo=datetime.timezone.utc)),
        ),
    ]
