# Generated by Django 4.2.16 on 2024-12-09 23:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_gathering', '0009_domainname_administrative_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domainname',
            old_name='administrative_contact',
            new_name='technical_contact',
        ),
        migrations.AlterField(
            model_name='domainname',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 9, 23, 21, 19, 394804, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='domainname',
            name='expire_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 9, 23, 21, 19, 394813, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='domainname',
            name='update_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 9, 23, 21, 19, 394810, tzinfo=datetime.timezone.utc)),
        ),
    ]
