# Generated by Django 4.2.16 on 2024-12-09 23:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_gathering', '0010_rename_administrative_contact_domainname_technical_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainname',
            name='administrative_contact',
            field=models.CharField(blank=True, default='none', max_length=64),
        ),
        migrations.AlterField(
            model_name='domainname',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 9, 23, 21, 46, 516103, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='domainname',
            name='expire_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 9, 23, 21, 46, 516112, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='domainname',
            name='update_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 9, 23, 21, 46, 516108, tzinfo=datetime.timezone.utc)),
        ),
    ]
