# Generated by Django 4.2.16 on 2024-12-15 14:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info_gathering', '0029_alter_domainname_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainname',
            name='administrative_contact',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, related_name='administrative', to='info_gathering.personinfo', to_field='name'),
        ),
        migrations.AlterField(
            model_name='domainname',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 15, 14, 32, 47, 949893, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='domainname',
            name='expire_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 15, 14, 32, 47, 950095, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='domainname',
            name='update_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 15, 14, 32, 47, 950091, tzinfo=datetime.timezone.utc)),
        ),
    ]
