# Generated by Django 4.2.16 on 2024-12-14 10:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info_gathering', '0027_alter_domainname_create_date_and_more'),
        ('ioc_management', '0024_alter_ipadd_expire_date_alter_vulnreview_cve'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=32, unique=True)),
                ('ipadd', models.CharField(max_length=32)),
                ('network_zone', models.CharField(choices=[('client', 'client'), ('server', 'server'), ('dmz', 'dmz'), ('public', 'public')], max_length=16)),
                ('behind_utm_firewall', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=16)),
                ('edr_active', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=16)),
                ('soc_scope', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=16)),
                ('sensitive_data', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=16)),
                ('business_impact', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], max_length=16)),
                ('end_of_life', models.DateField(default=datetime.datetime(2024, 12, 14, 10, 56, 36, 218833, tzinfo=datetime.timezone.utc))),
                ('description', models.TextField()),
                ('organization', models.ForeignKey(db_column='organization_name', on_delete=django.db.models.deletion.CASCADE, to='info_gathering.organizationinfo', to_field='organization_name')),
                ('owner', models.ForeignKey(db_column='name', on_delete=django.db.models.deletion.CASCADE, to='info_gathering.personinfo', to_field='name')),
            ],
        ),
        migrations.CreateModel(
            name='CriticalVuln',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ForeignKey(db_column='hostname', on_delete=django.db.models.deletion.CASCADE, to='infosec_dashboard.asset', to_field='hostname')),
                ('cve', models.ForeignKey(db_column='cve', on_delete=django.db.models.deletion.CASCADE, to='ioc_management.vulnreview', to_field='cve')),
                ('owner', models.ForeignKey(db_column='name', on_delete=django.db.models.deletion.CASCADE, to='info_gathering.personinfo', to_field='name')),
            ],
        ),
    ]
