# Generated by Django 4.2.16 on 2024-12-15 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infosec_dashboard', '0002_alter_asset_end_of_life'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='end_of_life',
            field=models.DateField(default=datetime.datetime(2024, 12, 15, 14, 32, 2, 945218, tzinfo=datetime.timezone.utc)),
        ),
    ]
