# Generated by Django 4.2.16 on 2024-12-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_rep', '0002_alter_ipadd_fqdn_alter_ipadd_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipadd',
            name='fqdn',
            field=models.CharField(blank=True, default='none', max_length=32),
        ),
        migrations.AlterField(
            model_name='ipadd',
            name='url',
            field=models.CharField(blank=True, default='none', max_length=32),
        ),
    ]
