# Generated by Django 4.2.16 on 2024-12-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_rep', '0003_alter_ipadd_fqdn_alter_ipadd_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipadd',
            name='ip_address',
            field=models.GenericIPAddressField(unique=True, unpack_ipv4=True),
        ),
    ]
