# Generated by Django 4.2.16 on 2024-12-06 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_rep', '0004_alter_ipadd_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipadd',
            name='expire_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 6, 22, 6, 23, 147973, tzinfo=datetime.timezone.utc)),
        ),
    ]
