<?php

include("./include.php");

// intro banner
$content  = "<!--**********************************\n";
$content .= "Content body start\n";
$content .= "***********************************-->\n";
$content .= "<div class=\"content-body\">\n";
$content .= "<div class=\"container-fluid\">\n";
$content .= "<div class=\"row page-titles mx-0\">\n";
$content .= "<div class=\"col-sm-6\">\n";
$content .= "<div class=\"welcome-text\">\n";
$content .= "<h4>Hi, welcome back!</h4>\n";
$content .= "<p class=\"mb-0\">Your business dashboard template</p>\n";
$content .= "</div>\n";
$content .= "</div>\n";
$content .= "<div class=\"col-sm-6 justify-content-sm-end mt-2 mt-sm-0 d-flex\">\n";
$content .= "<ol class=\"breadcrumb\">\n";
$content .= "<li class=\"breadcrumb-item\"><a href=\"javascript:void(0)\">Charts</a></li>\n";
$content .= "<li class=\"breadcrumb-item active\"><a href=\"javascript:void(0)\">ChartJS</a></li>\n";
$content .= "</ol>\n";
$content .= "</div>\n";
$content .= "</div>\n";
$content .= "<!-- row -->\n";

$content .= "<div class=\"row\">\n";
$content .= "<div class=\"col-12\">\n";
$content .= "<div class=\"row\">\n";
$content .= "<div class=\"col-lg-6 col-sm-6\">\n";
$content .= "<div class=\"card\">\n";
$content .= "<div class=\"card-header\">\n";
$content .= "<h4 class=\"card-title\">Basic Bar Chart</h4>\n";
$content .= "</div>\n";
$content .= "<div class=\"card-body\">\n";
$content .= "<canvas id=\"barChart_1\"></canvas>\n";
$content .= "</div>\n";
$content .= "</div>\n";
$content .= "</div>\n";
$content .= "<div class=\"col-lg-6 col-sm-6\">\n";
$content .= "<div class=\"card\">\n";
$content .= "<div class=\"card-header\">\n";
$content .= "<h4 class=\"card-title\">Gradient Bar Chart</h4>\n";
$content .= "</div>\n";
$content .= "<div class=\"card-body\">\n";
$content .= "<canvas id=\"barChart_2\"></canvas>\n";
$content .= "</div>\n";
$content .= "</div>\n";
$content .= "</div>\n";
$content .= "<div class=\"col-lg-6 col-sm-6\">\n";
$content .= "<div class=\"card\">\n";
$content .= "<div class=\"card-header\">\n";
$content .= "<h4 class=\"card-title\">Stalked Bar Chart</h4>\n";
$content .= "</div>\n";
$content .= "<div class=\"card-body\">\n";
$content .= "<canvas id=\"barChart_3\"></canvas>\n";
$content .= "</div>\n";
$content .= "</div>\n";
$content .= "</div>\n";
$content .= "<div class=\"col-lg-6 col-sm-6\">\n";
$content .= "<div class=\"card\">\n";
$content .= "<div class=\"card-header\">\n";
$content .= "<h4 class=\"card-title\">Basic Line Chart</h4>\n";
$content .= "</div>\n";
$content .= "<div class=\"card-body\">\n";
$content .= "<canvas id=\"lineChart_1\"></canvas>\n";
$content .= "</div>\n";
$content .= "</div>\n";
$content .= "</div>\n";
$content .= "<div class=\"col-lg-6 col-sm-6\">\n";
$content .= "<div class=\"card\">\n";
$content .= "<div class=\"card-header\">\n";
$content .= "<h4 class=\"card-title\">Gradient Line Chart</h4>\n";
$content .= "</div>\n";
$content .= "<div class=\"card-body\">\n";
$content .= "<canvas id=\"lineChart_2\"></canvas>\n";
$content .= "</div>\n";
$content .= "</div>\n";
$content .= "</div>\n";
$content .= "<div class=\"col-lg-6 col-sm-6\">\n";
$content .= "<div class=\"card\">\n";
$content .= "<div class=\"card-header\">\n";
$content .= "<h4 class=\"card-title\">Dual Line Chart</h4>\n";
$content .= "</div>\n";
$content .= "<div class=\"card-body\">\n";
$content .= "<canvas id=\"lineChart_3\"></canvas>\n";
$content .= "</div>\n";
$content .= "</div>\n";
$content .= "</div>\n";
$content .= "<div class=\"col-lg-6 col-sm-6\">\n";
$content .= "<div class=\"card\">\n";
$content .= "<div class=\"card-header\">\n";
$content .= "<h4 class=\"card-title\">Basic Area Chart</h4>\n";
$content .= "</div>\n";
$content .= "<div class=\"card-body\">\n";
$content .= "<canvas id=\"areaChart_1\"></canvas>\n";
$content .= "</div>\n";
$content .= "</div>\n";
$content .= "</div>\n";
$content .= "<div class=\"col-lg-6 col-sm-6\">\n";
$content .= "<div class=\"card\">\n";
$content .= "<div class=\"card-header\">\n";
$content .= "<h4 class=\"card-title\">Gradinet Area Chart</h4>\n";
$content .= "</div>\n";
$content .= "<div class=\"card-body\">\n";
$content .= "<canvas id=\"areaChart_2\"></canvas>\n";
$content .= "</div>\n";
$content .= "</div>\n";
$content .= "</div>\n";
$content .= "<div class=\"col-lg-6 col-sm-6\">\n";
$content .= "<div class=\"card\">\n";
$content .= "<div class=\"card-header\">\n";
$content .= "<h4 class=\"card-title\">Dual Area Chart</h4>\n";
$content .= "</div>\n";
$content .= "<div class=\"card-body\">\n";
$content .= "<canvas id=\"areaChart_3\"></canvas>\n";
$content .= "</div>\n";
$content .= "</div>\n";
$content .= "</div>\n";
$content .= "<div class=\"col-lg-6 col-sm-6\">\n";
$content .= "<div class=\"card\">\n";
$content .= "<div class=\"card-header\">\n";
$content .= "<h4 class=\"card-title\">Radar Chart</h4>\n";
$content .= "</div>\n";
$content .= "<div class=\"card-body\">\n";
$content .= "<canvas id=\"radar_chart\"></canvas>\n";
$content .= "</div>\n";
$content .= "</div>\n";
$content .= "</div>\n";
$content .= "<div class=\"col-lg-6 col-sm-6\">\n";
$content .= "<div class=\"card\">\n";
$content .= "<div class=\"card-header\">\n";
$content .= "<h4 class=\"card-title\">Pie Chart</h4>\n";
$content .= "</div>\n";
$content .= "<div class=\"card-body\">\n";
$content .= "<canvas id=\"pie_chart\"></canvas>\n";
$content .= "</div>\n";
$content .= "</div>\n";
$content .= "</div>\n";
$content .= "<div class=\"col-lg-6 col-sm-6\">\n";
$content .= "<div class=\"card\">\n";
$content .= "<div class=\"card-header\">\n";
$content .= "<h4 class=\"card-title\">Doughnut Chart</h4>\n";
$content .= "</div>\n";
$content .= "<div class=\"card-body\">\n";
$content .= "<canvas id=\"doughnut_chart\"></canvas>\n";
$content .= "</div>\n";
$content .= "</div>\n";
$content .= "</div>\n";
$content .= "<div class=\"col-lg-6 col-sm-6\">\n";
$content .= "<div class=\"card\">\n";
$content .= "<div class=\"card-header\">\n";
$content .= "<h4 class=\"card-title\">Polar Chart</h4>\n";
$content .= "</div>\n";
$content .= "<div class=\"card-body\">\n";
$content .= "<canvas id=\"polar_chart\"></canvas>\n";
$content .= "</div>\n";
$content .= "</div>\n";
$content .= "</div>\n";
$content .= "</div>\n";
$content .= "</div>\n";
$content .= "</div>\n";
$content .= "</div>\n";
$content .= "</div>\n";
$content .= "<!--**********************************\n";
$content .= "Content body end\n";
$content .= "***********************************-->\n";

$content .= "<!--**********************************\n";
$content .= "Support ticket button start\n";
$content .= "***********************************-->\n";

$content .= "<!--**********************************\n";
$content .= "Support ticket button end\n";
$content .= "***********************************-->\n";

$content .= "</div>\n";
$content .= "<!--**********************************\n";
$content .= "Main wrapper end\n";
$content .= "***********************************-->\n";

$content .= "<!--**********************************\n";
$content .= "Scripts\n";
$content .= "***********************************-->\n";
$content .= "<!-- Required vendors -->\n";
$content .= "<script src=\"./vendor/global/global.min.js\"></script>\n";
$content .= "<script src=\"./js/quixnav-init.js\"></script>\n";
$content .= "<script src=\"./js/custom.min.js\"></script>\n";

$content .= "<!-- Chart ChartJS plugin files -->\n";
$content .= "<script src=\"./vendor/chart.js/Chart.bundle.min.js\"></script>\n";
$content .= "<script src=\"./js/plugins-init/chartjs-init.js\"></script>\n";

echo $header;
echo add_body($content);
echo $footer;

?>