# Generated by Django 4.2.16 on 2024-12-07 17:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ipadd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True, unpack_ipv4=True)),
                ('url', models.CharField(blank=True, default='none', max_length=32)),
                ('fqdn', models.CharField(blank=True, default='none', max_length=32)),
                ('confidence', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='low', max_length=16)),
                ('description', models.TextField()),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('expire_date', models.DateField(default=datetime.datetime(2024, 12, 7, 17, 32, 3, 321234, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='Vuln',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('cvss', models.FloatField(default=0, null=True)),
                ('description', models.TextField()),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='VulnReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cve', models.ForeignKey(db_column='name', on_delete=django.db.models.deletion.CASCADE, to='ioc_management.vuln', to_field='name')),
            ],
        ),
    ]
