# Generated by Django 4.2.16 on 2024-12-08 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ioc_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipadd',
            name='expire_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 8, 16, 24, 48, 921341, tzinfo=datetime.timezone.utc)),
        ),
    ]
