# Generated by Django 4.2.16 on 2024-12-08 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ioc_management', '0002_alter_ipadd_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipadd',
            name='expire_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 8, 16, 29, 21, 605717, tzinfo=datetime.timezone.utc)),
        ),
    ]
