# Generated by Django 4.2.16 on 2024-12-11 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ioc_management', '0021_alter_ipadd_expire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnreview',
            name='lastchange_author',
            field=models.CharField(default=None, editable=False, max_length=32),
        ),
        migrations.AddField(
            model_name='vulnreview',
            name='references_list',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ipadd',
            name='expire_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 11, 16, 1, 21, 115452, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vulnreview',
            name='author',
            field=models.CharField(default=None, editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name='vulnreview',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
