# Generated by Django 4.2.16 on 2024-12-11 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ioc_management', '0022_vulnreview_lastchange_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipadd',
            name='author',
            field=models.CharField(default=None, editable=False, max_length=32),
        ),
        migrations.AddField(
            model_name='ipadd',
            name='lastchange_author',
            field=models.CharField(default=None, editable=False, max_length=32),
        ),
        migrations.AddField(
            model_name='vuln',
            name='author',
            field=models.CharField(default=None, editable=False, max_length=32),
        ),
        migrations.AddField(
            model_name='vuln',
            name='lastchange_author',
            field=models.CharField(default=None, editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name='ipadd',
            name='expire_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 11, 16, 4, 31, 593399, tzinfo=datetime.timezone.utc)),
        ),
    ]
