# Generated by Django 4.2.16 on 2024-12-15 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ioc_management', '0024_alter_ipadd_expire_date_alter_vulnreview_cve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipadd',
            name='expire_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 15, 14, 25, 55, 677636, tzinfo=datetime.timezone.utc)),
        ),
    ]
