# Generated by Django 4.2.16 on 2024-11-30 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vulns_review', '0003_alter_vuln_cve_vulnreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuln',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='vulnreview',
            name='cve',
            field=models.ForeignKey(db_column='name', on_delete=django.db.models.deletion.CASCADE, to='vulns_review.vuln', to_field='name'),
        ),
    ]
