# Generated by Django 4.2.16 on 2024-11-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulns_review', '0004_alter_vuln_name_alter_vulnreview_cve'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuln',
            name='cvss',
            field=models.FloatField(default=None),
        ),
    ]
