# Generated by Django 4.2.16 on 2024-11-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulns_review', '0005_vuln_cvss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuln',
            name='cvss',
            field=models.FloatField(default=1),
        ),
    ]
